let DB=null, state=JSON.parse(localStorage.getItem('toji_progress_v2')||'{}'), currentDay=0,currentExercise=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const photo=s=>s?`<img src="${esc(s)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:`<div class="missingbox">FOTO REAL AINDA EM CURADORIA.<br>Nenhuma ilustração será usada como substituta.</div>`;
function all(){return DB.exercises} function doneCount(){return Object.values(state).filter(Boolean).length}
function save(){localStorage.setItem('toji_progress_v2',JSON.stringify(state)); updateProgress();}
function updateProgress(){if(!DB)return;const n=doneCount(),t=DB.exercises.length,p=Math.round(n/t*100); $('#pct').textContent=p+'%';$('#fill').style.width=p+'%';$('#bigPct').textContent=p+'%';$('#bigBar').style.width=p+'%';$('#done').textContent=n;$('#total').textContent=t;$('#week').innerHTML=DB.workouts.map((w,i)=>{const d=w.items.filter((_,j)=>state[`${i}-${j}`]).length;return `<div class="weekday ${d===w.items.length?'done':''}"><b>D${i+1}</b><br>${d}/${w.items.length}</div>`}).join('');}
function go(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0);}
function dayCard(w,i){const d=w.items.filter((_,j)=>state[`${i}-${j}`]).length;return `<article class="daycard" onclick="openDay(${i})"><div class="daynum">DIA ${w.day}</div><h3>${esc(w.name)}</h3><p>${esc(w.focus)}</p><div class="daycount">${d}/${w.items.length} CONCLUÍDOS</div></article>`}
function renderHome(){ $('#days').innerHTML=DB.workouts.map(dayCard).join(''); updateProgress(); }
function renderProtocol(){ $('#protocolDays').innerHTML=DB.workouts.map(dayCard).join(''); }
function openDay(i){currentDay=i;const w=DB.workouts[i];$('#dayContent').innerHTML=`<div class="dayhero"><div class="daynum">DIA ${w.day}</div><h1>${esc(w.name)}</h1><p>${esc(w.focus)} • ${w.items.length} exercícios</p></div><div class="exercise-grid">${w.items.map((x,j)=>{const [name,equip,sets,rir,rest,cat,target,cue,key]=x;const e=DB.exercises.find(z=>z.id===`D${String(i+1).padStart(2,'0')}-E${String(j+1).padStart(2,'0')}`);const d=!!state[`${i}-${j}`];return `<article class="exercise-card" onclick="openExercise(${i},${j})"><div class="photo ${e?.photo_url?'':'missing'}">${e?.photo_url?photo(e.photo_url):'<div>FOTO REAL EM CURADORIA<br>SEM BONECOS</div>'}</div><div class="cardbody"><h3>${esc(name)}</h3><p>${esc(equip)} • ${esc(cat)}</p><div class="meta"><b>${esc(sets)}</b><span>${d?'✓ CONCLUÍDO':'ABRIR →'}</span></div></div></article>`}).join('')}</div>`;go('day');}
function openExercise(di,ei){currentDay=di;currentExercise=ei;const x=DB.workouts[di].items[ei];const [name,equip,sets,rir,rest,cat,target,cue,key]=x;const e=DB.exercises.find(z=>z.id===`D${String(di+1).padStart(2,'0')}-E${String(ei+1).padStart(2,'0')}`),d=!!state[`${di}-${ei}`];$('#exerciseContent').innerHTML=`<div class="eyebrow">DIA ${DB.workouts[di].day} • ${esc(cat).toUpperCase()}</div><h1>${esc(name)}</h1><div class="technical">${esc(equip)}</div><div class="detailphoto">${e?.photo_url?photo(e.photo_url):'<div class="missingbox">FOTO REAL EM CURADORIA.<br>Não será substituída por desenho ou boneco.</div>'}</div><div class="stats"><div class="stat"><b>${esc(sets)}</b><span>Séries × reps</span></div><div class="stat"><b>${esc(rir)}</b><span>RIR</span></div><div class="stat"><b>${esc(rest)}</b><span>Descanso</span></div></div><div class="info"><h3>MÚSCULO-ALVO</h3><p>${esc(target)}</p></div><div class="info"><h3>EXECUÇÃO / CUE</h3><p>${esc(cue)}</p></div><div class="source">${e?.photo_url?`Foto: ${esc(e.photo_credit)} • ${esc(e.photo_license)} • ${esc(e.photo_source)}`:'Sem foto publicada ainda — aguardando fonte fotográfica real verificada.'}</div><button class="complete ${d?'done':''}" onclick="toggleDone()">${d?'✓ EXERCÍCIO CONCLUÍDO':'MARCAR COMO CONCLUÍDO'}</button>`;go('exercise');}
function toggleDone(){const id=`${currentDay}-${currentExercise}`;state[id]=!state[id];save();openExercise(currentDay,currentExercise)}
function backToDay(){openDay(currentDay)}
async function init(){const r=await fetch('db.json',{cache:'no-store'});if(!r.ok)throw Error('db');DB=await r.json();$('#heroCount').textContent=DB.stats.exercises+' EXERCÍCIOS';$('#heroDays').textContent=DB.stats.days+' DIAS';$('#verified').textContent=DB.stats.verified_real_photos+' FOTOS REAIS VERIFICADAS';renderHome();renderProtocol();updateProgress();}
$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$('#start').addEventListener('click',()=>openDay(0));init().catch(e=>{document.body.innerHTML='<main style="padding:30px;color:white;font-family:system-ui"><h1>TOJI PROTOCOL</h1><p>Erro ao carregar o banco de dados.</p><p>Verifique se <b>db.json</b> está na raiz do projeto.</p></main>';console.error(e)});
