let DB=null;
let state=JSON.parse(localStorage.getItem('toji_progress_v3')||'{}');
let logs=JSON.parse(localStorage.getItem('toji_logs_v1')||'{}');
let currentDay=0,currentExercise=0;
const PREMIUM_CHECKOUT_URL=''; // Preencha depois com seu link de checkout real.
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const premium=()=>localStorage.getItem('toji_premium')==='true';
function photo(s,alt){return s?`<img src="${esc(s)}" alt="${esc(alt||'Foto real do exercício')}" loading="lazy" referrerpolicy="no-referrer" onerror="if(this.dataset.alt){this.src=this.dataset.alt;this.dataset.alt=''}else{this.replaceWith(Object.assign(document.createElement('div'),{className:'missingbox',innerHTML:'FOTO REAL TEMPORARIAMENTE INDISPONÍVEL.'}))}" data-alt="${esc(alt||'')}">`:`<div class="missingbox">FOTO REAL AINDA EM CURADORIA.<br>Nenhuma ilustração será usada como substituta.</div>`}
function doneCount(){return Object.values(state).filter(Boolean).length}
function save(){localStorage.setItem('toji_progress_v3',JSON.stringify(state));updateProgress();renderHome();renderProtocol();}
function saveLogs(){localStorage.setItem('toji_logs_v1',JSON.stringify(logs));}
function updateProgress(){if(!DB)return;const n=doneCount(),t=DB.exercises.length,p=Math.round(n/t*100);$('#pct').textContent=p+'%';$('#fill').style.width=p+'%';$('#bigPct').textContent=p+'%';$('#bigBar').style.width=p+'%';$('#done').textContent=n;$('#total').textContent=t;$('#week').innerHTML=DB.workouts.map((w,i)=>{const d=w.items.filter((_,j)=>state[`${i}-${j}`]).length;return `<div class="weekday ${d===w.items.length?'done':''}"><b>D${i+1}</b><br>${d}/${w.items.length}</div>`}).join('');$('#historyList').innerHTML=renderHistory();}
function go(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0);if(id==='progress')updateProgress();}
function dayCard(w,i){const d=w.items.filter((_,j)=>state[`${i}-${j}`]).length;return `<article class="daycard" onclick="openDay(${i})"><div class="daynum">DIA ${w.day}</div><h3>${esc(w.name)}</h3><p>${esc(w.focus)}</p><div class="daycount">${d}/${w.items.length} CONCLUÍDOS</div></article>`}
function renderHome(){if(!DB)return;$('#days').innerHTML=DB.workouts.map(dayCard).join('');updateProgress();}
function renderProtocol(){if(!DB)return;$('#protocolDays').innerHTML=DB.workouts.map(dayCard).join('');}
function openDay(i){currentDay=i;const w=DB.workouts[i];$('#dayContent').innerHTML=`<div class="dayhero"><div class="daynum">DIA ${w.day}</div><h1>${esc(w.name)}</h1><p>${esc(w.focus)} • ${w.items.length} exercícios</p></div><div class="exercise-grid">${w.items.map((x,j)=>{const [name,equip,sets,rir,rest,cat,target,cue,key]=x;const e=DB.exercises.find(z=>z.id===`D${String(i+1).padStart(2,'0')}-E${String(j+1).padStart(2,'0')}`);const d=!!state[`${i}-${j}`];return `<article class="exercise-card" onclick="openExercise(${i},${j})"><div class="photo ${e?.photo_url?'':'missing'}">${e?.photo_url?photo(e.photo_url,e.photo_url_alt):'<div>FOTO REAL EM CURADORIA<br>SEM BONECOS</div>'}</div><div class="cardbody"><h3>${esc(name)}</h3><p>${esc(equip)} • ${esc(cat)}</p><div class="meta"><b>${esc(sets)}</b><span>${d?'✓ CONCLUÍDO':'ABRIR →'}</span></div></div></article>`}).join('')}</div>`;go('day');}
function logKey(){return `${currentDay}-${currentExercise}`}
function openExercise(di,ei){currentDay=di;currentExercise=ei;const x=DB.workouts[di].items[ei];const [name,equip,sets,rir,rest,cat,target,cue,key]=x;const e=DB.exercises.find(z=>z.id===`D${String(di+1).padStart(2,'0')}-E${String(ei+1).padStart(2,'0')}`),d=!!state[`${di}-${ei}`],l=logs[logKey()]||{};const locked=!premium();$('#exerciseContent').innerHTML=`<div class="eyebrow">DIA ${DB.workouts[di].day} • ${esc(cat).toUpperCase()}</div><h1>${esc(name)}</h1><div class="technical">${esc(equip)}</div><div class="detailphoto">${e?.photo_url?photo(e.photo_url,e.photo_url_alt):'<div class="missingbox">FOTO REAL EM CURADORIA.<br>Não será substituída por desenho ou boneco.</div>'}</div><div class="stats"><div class="stat"><b>${esc(sets)}</b><span>Séries × reps</span></div><div class="stat"><b>${esc(rir)}</b><span>RIR</span></div><div class="stat"><b>${esc(rest)}</b><span>Descanso</span></div></div><div class="info"><h3>MÚSCULO-ALVO</h3><p>${esc(target)}</p></div><div class="info"><h3>EXECUÇÃO / CUE</h3><p>${esc(cue)}</p></div><div class="logbox ${locked?'locked':''}"><div class="loghead"><div><h3>REGISTRO DO TREINO</h3><p>${locked?'Recurso Premium':'Salve carga, reps, RIR e observações.'}</p></div><span class="premiumtag">${locked?'PREMIUM':'ATIVO'}</span></div>${locked?`<button class="premiumcta" onclick="go('premium')">DESBLOQUEAR REGISTRO AVANÇADO</button>`:`<div class="loggrid"><label>Carga<input id="load" value="${esc(l.load||'')}" placeholder="kg"></label><label>Reps<input id="reps" value="${esc(l.reps||'')}" placeholder="ex.: 10"></label><label>RIR real<input id="rirreal" value="${esc(l.rirreal||'')}" placeholder="ex.: 2"></label></div><label class="notes">Observações<textarea id="notes" placeholder="Como foi o exercício?">${esc(l.notes||'')}</textarea></label><button class="saveLog" onclick="saveLog()">SALVAR REGISTRO</button>`}</div><div class="source">${e?.photo_url?`Foto: ${esc(e.photo_credit)} • ${esc(e.photo_license)} • ${esc(e.photo_source)}`:'Sem foto publicada ainda — aguardando fonte fotográfica real verificada.'}</div><button class="complete ${d?'done':''}" onclick="toggleDone()">${d?'✓ EXERCÍCIO CONCLUÍDO':'MARCAR COMO CONCLUÍDO'}</button>`;go('exercise');}
function saveLog(){if(!premium()){go('premium');return}logs[logKey()]={load:$('#load').value.trim(),reps:$('#reps').value.trim(),rirreal:$('#rirreal').value.trim(),notes:$('#notes').value.trim(),updatedAt:new Date().toISOString()};saveLogs();openExercise(currentDay,currentExercise);}
function toggleDone(){const id=`${currentDay}-${currentExercise}`;state[id]=!state[id];save();openExercise(currentDay,currentExercise)}
function backToDay(){openDay(currentDay)}
function renderHistory(){const entries=Object.entries(logs).filter(([,v])=>v&&Object.values(v).some(Boolean));if(!entries.length)return '<div class="empty">Nenhum registro avançado ainda.</div>';return entries.slice(-10).reverse().map(([k,v])=>{const [di,ei]=k.split('-').map(Number),x=DB.workouts[di]?.items[ei];return x?`<div class="history"><b>${esc(x[0])}</b><span>${esc(v.load||'-')} kg • ${esc(v.reps||'-')} reps • RIR ${esc(v.rirreal||'-')}</span></div>`:''}).join('')}
function initPremium(){const active=premium();$('#premiumStatus').textContent=active?'PREMIUM ATIVO':'PLANO GRATUITO';$('#premiumStatus').className='badge '+(active?'active':'');$('#premiumButton').textContent=active?'PREMIUM ATIVO':'QUERO O PREMIUM';if(active)$('#premiumButton').onclick=()=>{};else $('#premiumButton').onclick=openCheckout;}
function openCheckout(){if(PREMIUM_CHECKOUT_URL){location.href=PREMIUM_CHECKOUT_URL;return}alert('O checkout ainda não foi conectado. Primeiro precisamos criar seu link de pagamento.');}
async function init(){const r=await fetch('db.json',{cache:'no-store'});if(!r.ok)throw Error('db');DB=await r.json();$('#heroCount').textContent=DB.stats.exercises+' EXERCÍCIOS';$('#heroDays').textContent=DB.stats.days+' DIAS';$('#verified').textContent=(DB.stats.real_photos_mapped||DB.stats.verified_real_photos)+' FOTOS REAIS MAPEADAS';renderHome();renderProtocol();updateProgress();initPremium();}
$$('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$('#start').addEventListener('click',()=>openDay(0));init().catch(e=>{document.body.innerHTML='<main style="padding:30px;color:white;font-family:system-ui"><h1>TOJI PROTOCOL</h1><p>Erro ao carregar o banco de dados.</p><p>Verifique se <b>db.json</b> está na raiz do projeto.</p></main>';console.error(e)});
